[project]
name = "cloud-run-proj"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "pyjwt[crypto]>=2.10.1",
    "uvicorn>=0.35.0",
    "cryptography>=41.0.0",
]
